### PR TITLE
Milestone1

### PR DESCRIPTION
**Pull request by El-Potato-Slayer**
# Milestone 1
Completed all the necessary requirements for the first milestone:

- removed unnecessary files
- added linters and fixed errors
- installed big.js package
- installed prop-types package
- added deploy site to readme

### CODE REVIEW

**Review by Berabjesus — CHANGES_REQUESTED** [review]
# Status: CHANGES REQUIRED :warning: :construction: 
Hello @El-Potato-Slayer great start to this milestone.
#### You have a few things to work on before you proceed to the next milestone.

- [x] Although you have stated that you have removed unnecessary files you still need to remove unused files like `reportWebVitals.js`, `setupTests.js` and such.
- [x] `prop-types` should be in dependencies and not in devDependencies

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

**Comment by El-Potato-Slayer** [comment]
@Berabjesus The `reportWebVitals.js` file is important, as I use it to report web vitals, but I'll remove it as requested. I've also looked within the darkest depths and crevices of my folders and soul, however, I cannot find `setupTest.js` file. Seems poetic that this file must exist at some level, yet it doesn't, don't you think? :3

I'm not removing the default icons and the `manifest.json` file, since I use them as a reference for when I create icons at the later stage of applications.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello team @El-Potato-Slayer 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights

- You communicated professionally on what you worked on and why, keep it up 💯  ✔️ 
- You have worked on the changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Comment by Berabjesus** [comment]
> @Berabjesus The `reportWebVitals.js` file is important, as I use it to report web vitals, but I'll remove it as requested. I've also looked within the darkest depths and crevices of my folders and soul, however, I cannot find `setupTest.js` file. Seems poetic that this file must exist at some level, yet it doesn't, don't you think? :3
> 
> I'm not removing the default icons and the `manifest.json` file, since I use them as a reference for when I create icons at the later stage of applications.

Hi @El-Potato-Slayer, If you feel like you need them, for whatever thing you assume you do, add them to .gitignore and make use out of them later on and as for the `setupTest.js` you can find it [here in your commit history](https://github.com/El-Potato-Slayer/react-calculator/tree/3e42c67902b2b890f160fd34c4fbf34c75741168/src),  nothing poetic about it. 👍

**Comment by El-Potato-Slayer** [comment]
@mimipeshy Thank you! Congratulations to me 🥳🎉

**Comment by El-Potato-Slayer** [comment]
> Hi @El-Potato-Slayer, If you feel like you need them, for whatever thing you assume you do, add them to .gitignore and make use out of them later on and as for the `setupTest.js` you can find it [here in your commit history](https://github.com/El-Potato-Slayer/react-calculator/tree/3e42c67902b2b890f160fd34c4fbf34c75741168/src), and yes, it's so poetic and beautiful. 😢

Thank you! I agree, it's very poetic. It's not easy to see the poeticness of something that's already been removed 😄

**Pull request merged**
